
<!DOCTYPE Product [
	<!ELEMENT Product (name,bodypart,price,date_creation)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT bodypart (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT date_creation (#PCDATA)>

]>

<Product>
	<name>wristech</name> 
	<bodypart>wrist </bodypart>
	<price>500</price>
	<date_creation>2010-05-04</date_creation>
	
</Product>