<!DOCTYPE Product [
	<!ELEMENT Product (name,bodypart,price,date_creation)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT bodypart (#PCDATA)>
	<!ELEMENT price (#PCDATA)>
	<!ELEMENT date_creation (#PCDATA)>

]>

<Product>
    <name>kneech</name>
    <bodypart>knee</bodypart>
    <price>1000.0</price>
    <date_creation>2021-04-05</date_creation>
</Product>
